version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - cd hotel-ws
      - mvn package
artifacts:
  files:
    - '**/*'
  base-directory: 'target/'
